FROM node:22.14.0-bullseye

ARG SSH_PRIVATE_KEY
ARG SERVER_HASH
ARG CI_COMMIT_BRANCH

ENV SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
ENV SERVER_HASH=${SERVER_HASH}
ENV CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}

WORKDIR /app
COPY . /app/

RUN sh ./ciScripts/buildAndPublishWip.sh