FROM node:22.14.0-bullseye

ARG SSH_PRIVATE_KEY
ARG SERVER_HASH
ARG CI_COMMIT_BRANCH
ARG NPM_TOKEN
ARG GBT_NPM_TOKEN

ENV SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
ENV SERVER_HASH=${SERVER_HASH}
ENV NPM_TOKEN=${NPM_TOKEN}
ENV GBT_NPM_TOKEN=${GBT_NPM_TOKEN}

WORKDIR /app
COPY . /app/

RUN bash ./ciScripts/publishNewVersion.sh